
FROM python:3.9
WORKDIR /TSTPredict
COPY requirements.txt /TSTPredict/requirements.txt
RUN pip install -r requirements.txt
COPY . /TSTPredict
EXPOSE 8080
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]